version: '3.8'

services:
  nextjs:
    container_name: nextjs
    build: ./client
    expose:
      - "3000"
    env_file:
      - ./client/.env.local
    networks:
      - app-network
    depends_on:
      - strapi

  strapi:
    container_name: strapi
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "1337"
    env_file:
      - ./server/.env
    volumes:
      - ./server/.tmp:/app/.tmp
      - ./server/public/uploads:/app/public/uploads
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Mount SSL certificates folder
    networks:
      - app-network
    depends_on:
      - nextjs
      - strapi


networks:
  app-network:
    driver: bridge
