import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/layout/navigation/navbar/header";
import { Toaster } from "@/components/ui/sonner";
import  { ConsentPopup } from "@/components/shared/popups/popup";
import Footer from "@/components/shared/layout/navigation/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NCSC",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex flex-col flex-1 w-full">
            {children}
          </main>
          <Footer />
          <ConsentPopup />
        </div>
        <Toaster />
        
      </body>
    </html>
  );
}
